services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CLIENT_URL=http://localhost
      - CLIENT_PORT=80
    ports:
      - 5000:5000
    expose:
      - 5000

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CLIENT_URL=http://localhost
      - CLIENT_PORT=80
    ports:
      - 4000:4000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 80:80
    expose:
      - 80
# docker compose -p chater up -d
