const chatTypes = {
    FETCH_CHAT_REQUEST: "FETCH_CHAT_REQUEST",
    FETCH_CHAT_SUCCESS: "FETCH_CHAT_SUCCESS",
    FETCH_CHAT_FAILURE: "FETCH_CHAT_FAILURE",
    DELETE_CHAT_REQUEST: "DELETE_CHAT_REQUEST",
    DELETE_CHAT_SUCCESS: "DELETE_CHAT_SUCCESS",
    DELETE_CHAT_FAILURE: "DELETE_CHAT_FAILURE",
}

export default chatTypes
