const confirmDialogTypes = {
    OPEN_CONFIRM_DIALOG: "OPEN_CONFIRM_DIALOG",
    CANCEL_CONFIRM_DIALOG: "CANCEL_CONFIRM_DIALOG",
    OK_CONFIRM_DIALOG_REQUEST: "OK_CONFIRM_DIALOG_REQUEST",
    OK_CONFIRM_DIALOG_SUCCESS: "OK_CONFIRM_DIALOG_SUCCESS",
    OK_CONFIRM_DIALOG_FAILURE: "OK_CONFIRM_DIALOG_FAILURE",
}

export default confirmDialogTypes
