export const chatTypes = {
    GET_LIST_CHATS: "GET_LIST_CHATS",
    GET_LIST_CHATS_SUCCESS: "GET_LIST_CHATS_SUCCESS",
    GET_LIST_CHATS_FAILED: "GET_LIST_CHATS_FAILED",

    DELETE_CHAT: "DELETE_CHAT",
    DELETE_CHAT_SUCCESS: "DELETE_CHAT_SUCCESS",
    DELETE_CHAT_FAILED: "DELETE_CHAT_FAILED",

    ADD_NEW_MESSAGE: "ADD_NEW_MESSAGE",
    DELETE_CHAT_STORE: "DELETE_CHAT_STORE",
}
