export const chatTypes = {
    GET_LIST_CHATS: "GET_LIST_CHATS",
    GET_LIST_CHATS_SUCCESS: "GET_LIST_CHATS_SUCCESS",
    GET_LIST_CHATS_FAILED: "GET_LIST_CHATS_FAILED",
    
    GET_CHAT: "GET_CHAT",
    GET_CHAT_SUCCESS: "GET_CHAT_SUCCESS",
    GET_CHAT_FAILED: "GET_CHAT_FAILED",
    GET_MESSAGES: "GET_MESSAGES",
    GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
    GET_MESSAGES_FAILED: "GET_MESSAGES_FAILED",
    ADD_MESSAGE: "ADD_MESSAGE",
}
