export const currentUserTypes = {
    CHECK_SESSION: "CHECK_SESSION",
    CHECK_SESSION_SUCCESS: "CHECK_SESSION_SUCCESS",
    CHECK_SESSION_FAILED: "CHECK_SESSION_FAILED",
    
    REFRESH: "REFRESH"
}
