export const currentUserTypes = {
    CHECK_SESSION: "CHECK_SESSION",
    CHECK_SESSION_SUCCESS: "CHECK_SESSION_SUCCESS",
    CHECK_SESSION_FAILED: "CHECK_SESSION_FAILED",

    DELETE_FRIEND_STORE: "DELETE_FRIEND_STORE",

    REFRESH: "REFRESH",
}
