export const inviteTypes = {
    GET_LIST_INVITES: "GET_LIST_INVITES",
    GET_LIST_INVITES_SUCCESS: "GET_LIST_INVITES_SUCCESS",
    GET_LIST_INVITES_FAILED: "GET_LIST_INVITES_FAILED",
    ACCEPT_INVITE: "ACCEPT_INVITE",
    ACCEPT_INVITE_SUCCESS: "ACCEPT_INVITE_SUCCESS",
    ACCEPT_INVITE_FAILED: "ACCEPT_INVITE_FAILED",
    REJECT_INVITE: "REJECT_INVITE",
    REJECT_INVITE_SUCCESS: "REJECT_INVITE_SUCCESS",
    REJECT_INVITE_FAILED: "REJECT_INVITE_FAILED",
}
