export const inviteTypes = {
    // Get invites
    GET_LIST_INVITES: "GET_LIST_INVITES",
    GET_LIST_INVITES_SUCCESS: "GET_LIST_INVITES_SUCCESS",
    GET_LIST_INVITES_FAILED: "GET_LIST_INVITES_FAILED",

    // Send invite
    SEND_INVITE: "SEND_INVITE",
    SEND_INVITE_SUCCESS: "SEND_INVITE_SUCCESS",
    SEND_INVITE_FAILED: "SEND_INVITE_FAILED",

    // Accept Invite
    ACCEPT_INVITE: "ACCEPT_INVITE",
    ACCEPT_INVITE_SUCCESS: "ACCEPT_INVITE_SUCCESS",
    ACCEPT_INVITE_FAILED: "ACCEPT_INVITE_FAILED",

    REJECT_INVITE: "REJECT_INVITE",
    REJECT_INVITE_SUCCESS: "REJECT_INVITE_SUCCESS",
    REJECT_INVITE_FAILED: "REJECT_INVITE_FAILED",
}
