export const suggestFriendTypes = {
    GET_SUGGEST_FRIENDS: "GET_SUGGEST_FRIENDS",
    GET_SUGGEST_FRIENDS_SUCCESS: "GET_SUGGEST_FRIENDS_SUCCESS",
    GET_SUGGEST_FRIENDS_FAILED: "GET_SUGGEST_FRIENDS_FAILED",
}
