export const types = {
    GET_CURRENT_USER: "GET_CURRENT_USER",
    GET_CURRENT_USER_SUCCEEDED: "GET_CURRENT_USER_SUCCEEDED",
    GET_CURRENT_USER_FAILED: "GET_CURRENT_USER_FAILED",

    GET_USER: "GET_USER",
    GET_USER_SUCCEEDED: "GET_USER_SUCCEEDED",
    GET_USER_FAILED: "GET_USER_FAILED",

    ADD_FRIEND: "ADD_FRIEND",
    ADD_FRIEND_SUCCEEDED: "ADD_FRIEND_SUCCEEDED",
    ADD_FRIEND_FAILED: "ADD_FRIEND_FAILED",

    USER_LOGIN_FAILED: "USER_LOGIN_FAILED",

    LOGOUT: "LOGOUT",

    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILURE: "SEARCH_FAILURE",

    ACCEPT_FRIEND_REQUEST: "ACCEPT_FRIEND_REQUEST",
    ACCEPT_FRIEND_SUCCESS: "ACCEPT_FRIEND_SUCCESS",
    ACCEPT_FRIEND_FAILURE: "ACCEPT_FRIEND_FAILURE",
    REJECT_FRIEND_REQUEST: "REJECT_FRIEND_REQUEST",
    REJECT_FRIEND_SUCCESS: "REJECT_FRIEND_SUCCESS",
    REJECT_FRIEND_FAILURE: "REJECT_FRIEND_FAILURE",

    DELETE_FRIEND_REQUEST: "DELETE_FRIEND_REQUEST",
    DELETE_FRIEND_SUCCESS: "DELETE_FRIEND_SUCCESS",
    DELETE_FRIEND_FAILURE: "DELETE_FRIEND_FAILURE",

    GET_SUGGEST_FRIENDS: "GET_SUGGEST_FRIENDS",
    GET_SUGGEST_FRIENDS_SUCCEEDED: "GET_SUGGEST_FRIENDS_SUCCEEDED",
    GET_SUGGEST_FRIENDS_FAILED: "GET_SUGGEST_FRIENDS_FAILED",
}
