export const userTypes = {
    // Get user
    GET_USER: "GET_USER",
    GET_USER_SUCCEEDED: "GET_USER_SUCCEEDED",
    GET_USER_FAILED: "GET_USER_FAILED",

    // Logout
    LOGOUT: "LOGOUT",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILED: "LOGOUT_FAILED",

    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILURE: "SEARCH_FAILURE",

    ACCEPT_FRIEND_REQUEST: "ACCEPT_FRIEND_REQUEST",
    ACCEPT_FRIEND_SUCCESS: "ACCEPT_FRIEND_SUCCESS",
    ACCEPT_FRIEND_FAILURE: "ACCEPT_FRIEND_FAILURE",

    REJECT_FRIEND_REQUEST: "REJECT_FRIEND_REQUEST",
    REJECT_FRIEND_SUCCESS: "REJECT_FRIEND_SUCCESS",
    REJECT_FRIEND_FAILURE: "REJECT_FRIEND_FAILURE",

    DELETE_FRIEND_REQUEST: "DELETE_FRIEND_REQUEST",
    DELETE_FRIEND_SUCCESS: "DELETE_FRIEND_SUCCESS",
    DELETE_FRIEND_FAILURE: "DELETE_FRIEND_FAILURE",
}
