const ActionTypes = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCEEDED: "USER_LOGIN_SUCCEEDED",
    USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
    FETCH_USER: "FETCH_USER",
    FETCH_USER_SUCCEEDED: "FETCH_USER_SUCCEEDED",
    FETCH_USER_FAILED: "FETCH_USER_FAILED",
}

export default ActionTypes
