const ActionTypes = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCEEDED: "USER_LOGIN_SUCCEEDED",
    USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
    LOGOUT: "LOGOUT",
    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILURE: "SEARCH_FAILURE",
    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",
    FRIEND_REQUEST: "FRIEND_REQUEST",
    FRIEND_REQUEST_SUCCESS: "FRIEND_REQUEST_SUCCESS",
    FRIEND_REQUEST_FAILURE: "FRIEND_REQUEST_FAILURE",
    ACCEPT_FRIEND_REQUEST: "ACCEPT_FRIEND_REQUEST",
    ACCEPT_FRIEND_SUCCESS: "ACCEPT_FRIEND_SUCCESS",
    ACCEPT_FRIEND_FAILURE: "ACCEPT_FRIEND_FAILURE",
    REJECT_FRIEND_REQUEST: "REJECT_FRIEND_REQUEST",
    REJECT_FRIEND_SUCCESS: "REJECT_FRIEND_SUCCESS",
    REJECT_FRIEND_FAILURE: "REJECT_FRIEND_FAILURE",

    DELETE_FRIEND_REQUEST: "DELETE_FRIEND_REQUEST",
    DELETE_FRIEND_SUCCESS: "DELETE_FRIEND_SUCCESS",
    DELETE_FRIEND_FAILURE: "DELETE_FRIEND_FAILURE",
}

export default ActionTypes
